services:
  postgres:
    container_name: civalgo_postgres
    image: postgres
    environment:
      POSTGRES_DB: civalgo_postgres_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    container_name: civalgo_nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3000'
    volumes:
      - .:/app
    depends_on:
      - postgres
